In [1]:
import pandas as pd

In [12]:
df = pd.read_csv('data/03-28_to_04-27_rm354_FPB.csv')

In [13]:
df.head()

,dateTime,pointDisplayName,point_id,unit,dateTimeUtc,pointName,pointKind,value,deviceName,pointField
0,03/29/2026 00:00:00,Discharge Air Flow,673ce924ffc77731fa3ed999,cfm,03/29/2026 05:00:00,AirFl,Number,1110.425659,FPB-01-018_354,discharge_air_flowrate_sensor
1,03/29/2026 00:00:00,Zone CO2,673ce924ffc77731fa3ed9a5,ppm,03/29/2026 05:00:00,RmCO2,Number,434.000000,FPB-01-018_354,zone_air_co2_concentration_sensor
2,03/29/2026 00:00:30,Zone CO2,673ce924ffc77731fa3ed9a5,ppm,03/29/2026 05:00:30,RmCO2,Number,433.000000,FPB-01-018_354,zone_air_co2_concentration_sensor
3,03/29/2026 00:01:01,Discharge Air Flow,673ce924ffc77731fa3ed999,cfm,03/29/2026 05:01:01,AirFl,Number,1099.938599,FPB-01-018_354,discharge_air_flowrate_sensor
4,03/29/2026 00:01:30,Zone CO2,673ce924ffc77731fa3ed9a5,ppm,03/29/2026 05:01:30,RmCO2,Number,432.000000,FPB-01-018_354,zone_air_co2_concentration_sensor

In [14]:
df['dateTime'] = pd.to_datetime(df['dateTime'])

In [15]:
df = df.sort_values("dateTime").reset_index(drop=True)
df = df.set_index("dateTime")

In [16]:
df.head()

,pointDisplayName,point_id,unit,dateTimeUtc,pointName,pointKind,value,deviceName,pointField
dateTime,,,,,,,,,
2026-03-29 00:00:00,Discharge Air Flow,673ce924ffc77731fa3ed999,cfm,03/29/2026 05:00:00,AirFl,Number,1110.425659,FPB-01-018_354,discharge_air_flowrate_sensor
2026-03-29 00:00:00,Zone CO2,673ce924ffc77731fa3ed9a5,ppm,03/29/2026 05:00:00,RmCO2,Number,434.000000,FPB-01-018_354,zone_air_co2_concentration_sensor
2026-03-29 00:00:30,Zone CO2,673ce924ffc77731fa3ed9a5,ppm,03/29/2026 05:00:30,RmCO2,Number,433.000000,FPB-01-018_354,zone_air_co2_concentration_sensor
2026-03-29 00:01:01,Discharge Air Flow,673ce924ffc77731fa3ed999,cfm,03/29/2026 05:01:01,AirFl,Number,1099.938599,FPB-01-018_354,discharge_air_flowrate_sensor
2026-03-29 00:01:30,Zone CO2,673ce924ffc77731fa3ed9a5,ppm,03/29/2026 05:01:30,RmCO2,Number,432.000000,FPB-01-018_354,zone_air_co2_concentration_sensor

In [17]:
df = df.drop(columns=['pointDisplayName', 'point_id', 'dateTimeUtc', 'pointName', 'pointKind', 'deviceName', 'pointField'])

In [18]:
df.head()

                    unit        value
dateTime
2026-03-29 00:00:00  cfm  1110.425659
2026-03-29 00:00:00  ppm   434.000000
2026-03-29 00:00:30  ppm   433.000000
2026-03-29 00:01:01  cfm  1099.938599
2026-03-29 00:01:30  ppm   432.000000

In [11]:
start = pd.Timestamp("2026-04-13 07:54:00")
end   = pd.Timestamp("2026-04-13 10:57:00")

df = df.loc[start:end].sort_index()

In [19]:
df.head(50)

                    unit        value
dateTime
2026-03-29 00:00:00  cfm  1110.425659
2026-03-29 00:00:00  ppm   434.000000
2026-03-29 00:00:30  ppm   433.000000
2026-03-29 00:01:01  cfm  1099.938599
2026-03-29 00:01:30  ppm   432.000000
2026-03-29 00:03:00  ppm   431.000000
2026-03-29 00:04:00  ppm   430.000000
2026-03-29 00:04:30  cfm  1107.480591
2026-03-29 00:05:01  cfm  1097.360352
2026-03-29 00:05:01  ppm   431.000000
2026-03-29 00:05:30  ppm   432.000000
2026-03-29 00:06:30  cfm  1089.984741
2026-03-29 00:06:30  ppm   434.000000
2026-03-29 00:07:01  ppm   435.000000
2026-03-29 00:07:31  cfm  1098.892578
2026-03-29 00:07:31  ppm   433.000000
2026-03-29 00:08:31  cfm  1099.953979
2026-03-29 00:08:31  ppm   432.000000
2026-03-29 00:08:31  %RH    21.900000
2026-03-29 00:08:31   °F    68.360001
2026-03-29 00:09:31  ppm   433.000000
2026-03-29 00:10:01  ppm   435.000000
2026-03-29 00:10:31  ppm   433.000000
2026-03-29 00:11:31  ppm   434.000000
2026-03-29 00:12:31  ppm   432.000000
2026-03-29 00:13:31  ppm   431.000000
2026-03-29 00:14:01  ppm   433.000000
2026-03-29 00:14:31  cfm  1105.578369
2026-03-29 00:14:31  ppm   431.000000
2026-03-29 00:15:31  cfm  1097.873901
2026-03-29 00:15:31  ppm   433.000000
2026-03-29 00:16:01  ppm   432.000000
2026-03-29 00:16:31  ppm   433.000000
2026-03-29 00:16:31  cfm  1104.249512
2026-03-29 00:18:01  ppm   434.000000
2026-03-29 00:19:01  cfm  1097.724609
2026-03-29 00:19:01  ppm   433.000000
2026-03-29 00:20:01  cfm  1103.087769
2026-03-29 00:20:01  ppm   434.000000
2026-03-29 00:21:31  ppm   433.000000
2026-03-29 00:23:01  cfm  1093.007202
2026-03-29 00:23:31  cfm  1098.862549
2026-03-29 00:24:31  ppm   434.000000
2026-03-29 00:25:01  ppm   435.000000
2026-03-29 00:25:31  ppm   434.000000
2026-03-29 00:26:01  ppm   435.000000
2026-03-29 00:26:31  cfm  1109.893433
2026-03-29 00:26:31  ppm   434.000000
2026-03-29 00:27:01  cfm  1102.045166
2026-03-29 00:28:01  cfm  1111.334351

In [20]:
df = (
    df.pivot_table(index=df.index, columns="unit", values="value", aggfunc="mean")
    .resample("1min").mean()
    .ffill()
    .bfill()
    .rename(columns={"cfm": "air_flow", "ppm": "co2", "%RH": "humidity", "°F": "temperature"})
    .rename_axis(columns=None)
    .rename_axis("time")
)

## Data Cleaning & Transformation Summary

The raw CSV exported from KODE contains one row per sensor reading in long format (each row is a single timestamped value tagged with a unit). The following steps reshape it into a clean wide-format time series:

1. **Parse timestamps** — `dateTime` is converted from a string to a proper `datetime` object so it can be used as a time index.
2. **Sort and index** — rows are sorted chronologically and `dateTime` is set as the index.
3. **Drop metadata columns** — columns not needed for analysis (`pointDisplayName`, `point_id`, `dateTimeUtc`, `pointName`, `pointKind`, `deviceName`, `pointField`) are removed, leaving only `unit` and `value`.
4. **Trim to occupied window** — rows outside the class session window (07:54–10:57) are dropped to focus on the period with people in the room.
5. **Pivot to wide format** — `pivot_table` rotates each unit (`ppm`, `cfm`, `%RH`, `°F`) into its own column. Where multiple readings fall in the same second, their mean is taken.
6. **Resample to 1-minute bins** — irregular sub-minute readings are aggregated into uniform 1-minute intervals, making the time series regular.
7. **Forward-fill gaps** — sensors report at different cadences (CO2 and air flow ~every 30 s; humidity and temperature ~every few minutes). `ffill` propagates the last known reading into empty bins so every row is complete.
8. **Rename columns** — unit abbreviations are replaced with descriptive names: `air_flow` (cfm), `co2` (ppm), `humidity` (%RH), `temperature` (°F).

In [21]:
df.head(50)

                     humidity     air_flow    co2  temperature
time
2026-03-29 00:00:00      21.9  1110.425659  433.5    68.360001
2026-03-29 00:01:00      21.9  1099.938599  432.0    68.360001
2026-03-29 00:02:00      21.9  1099.938599  432.0    68.360001
2026-03-29 00:03:00      21.9  1099.938599  431.0    68.360001
2026-03-29 00:04:00      21.9  1107.480591  430.0    68.360001
2026-03-29 00:05:00      21.9  1097.360352  431.5    68.360001
2026-03-29 00:06:00      21.9  1089.984741  434.0    68.360001
2026-03-29 00:07:00      21.9  1098.892578  434.0    68.360001
2026-03-29 00:08:00      21.9  1099.953979  432.0    68.360001
2026-03-29 00:09:00      21.9  1099.953979  433.0    68.360001
2026-03-29 00:10:00      21.9  1099.953979  434.0    68.360001
2026-03-29 00:11:00      21.9  1099.953979  434.0    68.360001
2026-03-29 00:12:00      21.9  1099.953979  432.0    68.360001
2026-03-29 00:13:00      21.9  1099.953979  431.0    68.360001
2026-03-29 00:14:00      21.9  1105.578369  432.0    68.360001
2026-03-29 00:15:00      21.9  1097.873901  433.0    68.360001
2026-03-29 00:16:00      21.9  1104.249512  432.5    68.360001
2026-03-29 00:17:00      21.9  1104.249512  432.5    68.360001
2026-03-29 00:18:00      21.9  1104.249512  434.0    68.360001
2026-03-29 00:19:00      21.9  1097.724609  433.0    68.360001
2026-03-29 00:20:00      21.9  1103.087769  434.0    68.360001
2026-03-29 00:21:00      21.9  1103.087769  433.0    68.360001
2026-03-29 00:22:00      21.9  1103.087769  433.0    68.360001
2026-03-29 00:23:00      21.9  1095.934875  433.0    68.360001
2026-03-29 00:24:00      21.9  1095.934875  434.0    68.360001
2026-03-29 00:25:00      21.9  1095.934875  434.5    68.360001
2026-03-29 00:26:00      21.9  1109.893433  434.5    68.360001
2026-03-29 00:27:00      21.9  1102.045166  434.5    68.360001
2026-03-29 00:28:00      21.9  1108.603271  435.5    68.360001
2026-03-29 00:29:00      21.9  1117.583618  434.0    68.360001
2026-03-29 00:30:00      21.9  1117.583618  434.5    68.360001
2026-03-29 00:31:00      21.9  1126.092773  435.5    68.360001
2026-03-29 00:32:00      21.9  1126.092773  435.0    68.360001
2026-03-29 00:33:00      21.9  1111.036072  435.5    68.360001
2026-03-29 00:34:00      21.9  1099.396118  435.5    68.360001
2026-03-29 00:35:00      21.9  1090.699097  435.5    68.360001
2026-03-29 00:36:00      21.9  1090.699097  436.5    68.360001
2026-03-29 00:37:00      21.9  1101.114624  436.5    68.360001
2026-03-29 00:38:00      21.9  1101.114624  435.0    68.360001
2026-03-29 00:39:00      21.9  1094.005127  435.5    68.360001
2026-03-29 00:40:00      21.9  1094.005127  437.0    68.360001
2026-03-29 00:41:00      21.9  1098.975586  436.0    68.360001
2026-03-29 00:42:00      21.9  1098.975586  436.5    68.360001
2026-03-29 00:43:00      21.9  1104.484009  436.5    68.360001
2026-03-29 00:44:00      21.9  1117.421997  437.0    68.360001
2026-03-29 00:45:00      21.9  1101.162170  437.5    68.360001
2026-03-29 00:46:00      21.9  1101.162170  436.0    68.360001
2026-03-29 00:47:00      21.9  1090.417847  436.0    68.360001
2026-03-29 00:48:00      21.9  1095.977051  436.0    68.360001
2026-03-29 00:49:00      21.9  1109.370239  438.0    68.360001

In [22]:
df.to_csv("data/03-28_to_04-27_rm354_FPB(cleaned).csv", index=True)

In [16]:
vb = pd.read_csv("data/4-13-2026 754am-358pm.txt", sep="\t", header=None, names=[" C8-1(v)", "C13-1(v)", "C8-7(v)", "C13-7(v)"])

In [17]:
start = pd.Timestamp("2026-04-13 07:54:00")
vb["time"] = start + pd.to_timedelta(range(len(vb)), unit="us") * 100

In [18]:
print(vb.head())

    C8-1(v)  C13-1(v)   C8-7(v)  C13-7(v)                       time
0  0.000105 -0.000426  0.002967  0.000156 2026-04-13 07:54:00.000000
1  0.000050 -0.000432  0.002936  0.000180 2026-04-13 07:54:00.000100
2  0.000051 -0.000398  0.002916  0.000163 2026-04-13 07:54:00.000200
3  0.000063 -0.000429  0.002952  0.000156 2026-04-13 07:54:00.000300
4  0.000020 -0.000442  0.002921  0.000160 2026-04-13 07:54:00.000400

In [19]:
vb.index = vb["time"]
vb = vb.drop(columns='time')

# Resample to 1-minute intervals — pick your aggregation
df_1min = vb.resample('1min').apply(lambda x: (x**2).mean()**0.5)

In [20]:
df_1min.head()

                      C8-1(v)  C13-1(v)   C8-7(v)  C13-7(v)
time
2026-04-13 07:54:00  0.001061  0.000551  0.002690  0.000534
2026-04-13 07:55:00  0.001080  0.000554  0.002699  0.000533
2026-04-13 07:56:00  0.001058  0.000537  0.002699  0.000508
2026-04-13 07:57:00  0.001046  0.000547  0.002701  0.000507
2026-04-13 07:58:00  0.000990  0.000559  0.002698  0.000512

In [21]:
start = pd.Timestamp("2026-04-13 07:54:00")
df_1min.index = df_1min.index.floor('min')

combined = df.join(df_1min, how='left')

In [22]:
print(combined.tail(50))

                      humidity     air_flow    co2  temperature   C8-1(v)  \
time
2026-04-13 10:07:00  49.400002  1109.398071  517.0    72.319999  0.001082
2026-04-13 10:08:00  49.400002  1117.538086  514.5    72.319999  0.001021
2026-04-13 10:09:00  49.400002  1117.538086  515.5    72.319999  0.001133
2026-04-13 10:10:00  49.400002  1204.961060  517.5    72.319999  0.000993
2026-04-13 10:11:00  49.400002  1210.984070  518.0    72.319999  0.000982
2026-04-13 10:12:00  49.400002  1210.984070  518.5    72.319999  0.000977
2026-04-13 10:13:00  49.400002  1210.984070  512.5    72.319999  0.000978
2026-04-13 10:14:00  49.400002  1210.984070  510.5    72.319999  0.001003
2026-04-13 10:15:00  49.400002  1197.864136  508.5    72.319999  0.001041
2026-04-13 10:16:00  49.400002  1214.729919  511.0    72.319999  0.001073
2026-04-13 10:17:00  49.400002  1218.659302  510.5    72.319999  0.001073
2026-04-13 10:18:00  49.400002  1209.541870  516.0    72.319999  0.001034
2026-04-13 10:19:00  49.400002  1209.541870  514.0    72.319999  0.001091
2026-04-13 10:20:00  49.400002  1216.652100  513.0    72.319999  0.001065
2026-04-13 10:21:00  49.400002  1216.652100  513.0    72.319999  0.001068
2026-04-13 10:22:00  49.400002  1340.669495  527.0    72.319999  0.001073
2026-04-13 10:23:00  49.400002  1416.189514  523.0    72.319999  0.001035
2026-04-13 10:24:00  49.400002  1415.547546  563.5    72.319999  0.001012
2026-04-13 10:25:00  49.400002  1424.040039  540.0    72.319999  0.001044
2026-04-13 10:26:00  49.400002  1416.539917  520.5    72.319999  0.001038
2026-04-13 10:27:00  49.400002  1418.069519  515.5    72.319999  0.001041
2026-04-13 10:28:00  49.400002  1418.069519  517.0    72.319999  0.001090
2026-04-13 10:29:00  49.400002  1418.069519  517.0    72.319999  0.001818
2026-04-13 10:30:00  49.400002  1420.916138  520.0    72.319999  0.001581
2026-04-13 10:31:00  49.400002  1420.916138  519.0    72.319999  0.001202
2026-04-13 10:32:00  49.400002  1420.916138  520.0    72.319999  0.001134
2026-04-13 10:33:00  49.400002  1428.025269  518.0    72.319999  0.001073
2026-04-13 10:34:00  49.400002  1428.025269  518.0    72.319999  0.001019
2026-04-13 10:35:00  49.850000  1428.025269  522.0    72.319999  0.001027
2026-04-13 10:36:00  49.850000  1428.025269  522.0    72.319999  0.001040
2026-04-13 10:37:00  49.850000  1415.831665  521.0    72.319999  0.000995
2026-04-13 10:38:00  50.500000  1415.831665  562.0    72.319999  0.000983
2026-04-13 10:39:00  49.400002  1430.249268  537.0    72.319999  0.001041
2026-04-13 10:40:00  50.900002  1621.940063  566.5    72.860001  0.001188
2026-04-13 10:41:00  50.900002  1430.908569  782.0    72.860001  0.001398
2026-04-13 10:42:00  49.400002  1402.826172  569.5    72.860001  0.001159
2026-04-13 10:43:00  49.400002  1528.464600  546.5    72.860001  0.001004
2026-04-13 10:44:00  50.500000  1646.036499  688.5    72.860001  0.001017
2026-04-13 10:45:00  50.500000  1418.246338  750.5    72.860001  0.001019
2026-04-13 10:46:00  49.400002  1404.991333  584.0    72.860001  0.001013
2026-04-13 10:47:00  49.400002  1605.883545  545.5    72.860001  0.001003
2026-04-13 10:48:00  51.299999  1608.982605  612.0    72.860001  0.001007
2026-04-13 10:49:00  51.299999  1419.101257  617.5    72.860001  0.001044
2026-04-13 10:50:00  49.500000  1421.328003  549.0    72.860001  0.001101
2026-04-13 10:51:00  49.500000  1431.504517  538.0    72.860001  0.001115
2026-04-13 10:52:00  49.500000  1406.785706  545.0    72.860001  0.001134
2026-04-13 10:53:00  50.599998  1406.785706  597.0    72.860001  0.001250
2026-04-13 10:54:00  51.949999  1314.476196  832.0    72.500000  0.001222
2026-04-13 10:55:00  51.949999  1127.730713  861.5    72.500000  0.001125
2026-04-13 10:56:00  50.400002  1127.730713  803.5    72.500000  0.001107

                     C13-1(v)   C8-7(v)  C13-7(v)
time
2026-04-13 10:07:00  0.000532  0.002686  0.000454
2026-04-13 10:08:00  0.000533  0.002688  0.000455
2026-04-13 10:09:00  0.000527  0.002693  0.000460
2026-04-13 10:10:00  0.000529  0.002685  0.000460
2026-04-13 10:11:00  0.000528  0.002688  0.000460
2026-04-13 10:12:00  0.000531  0.002697  0.000460
2026-04-13 10:13:00  0.000522  0.002681  0.000450
2026-04-13 10:14:00  0.000526  0.002685  0.000444
2026-04-13 10:15:00  0.000525  0.002692  0.000456
2026-04-13 10:16:00  0.000526  0.002689  0.000459
2026-04-13 10:17:00  0.000526  0.002694  0.000455
2026-04-13 10:18:00  0.000526  0.002695  0.000443
2026-04-13 10:19:00  0.000535  0.002695  0.000457
2026-04-13 10:20:00  0.000523  0.002695  0.000451
2026-04-13 10:21:00  0.000535  0.002708  0.000473
2026-04-13 10:22:00  0.000534  0.002705  0.000468
2026-04-13 10:23:00  0.000544  0.002704  0.000476
2026-04-13 10:24:00  0.000538  0.002701  0.000460
2026-04-13 10:25:00  0.000538  0.002708  0.000463
2026-04-13 10:26:00  0.000531  0.002700  0.000472
2026-04-13 10:27:00  0.000535  0.002696  0.000462
2026-04-13 10:28:00  0.000538  0.002697  0.000476
2026-04-13 10:29:00  0.000551  0.002716  0.000499
2026-04-13 10:30:00  0.000550  0.002711  0.000492
2026-04-13 10:31:00  0.000539  0.002698  0.000477
2026-04-13 10:32:00  0.000543  0.002690  0.000471
2026-04-13 10:33:00  0.000543  0.002690  0.000466
2026-04-13 10:34:00  0.000535  0.002687  0.000460
2026-04-13 10:35:00  0.000536  0.002681  0.000463
2026-04-13 10:36:00  0.000545  0.002694  0.000492
2026-04-13 10:37:00  0.000547  0.002688  0.000469
2026-04-13 10:38:00  0.000534  0.002686  0.000444
2026-04-13 10:39:00  0.000522  0.002681  0.000436
2026-04-13 10:40:00  0.000537  0.002678  0.000449
2026-04-13 10:41:00  0.000525  0.002672  0.000429
2026-04-13 10:42:00  0.000529  0.002685  0.000429
2026-04-13 10:43:00  0.000530  0.002682  0.000435
2026-04-13 10:44:00  0.000538  0.002682  0.000436
2026-04-13 10:45:00  0.000535  0.002661  0.000423
2026-04-13 10:46:00  0.000538  0.002663  0.000446
2026-04-13 10:47:00  0.000541  0.002673  0.000451
2026-04-13 10:48:00  0.000552  0.002693  0.000450
2026-04-13 10:49:00  0.000551  0.002681  0.000453
2026-04-13 10:50:00  0.000555  0.002697  0.000465
2026-04-13 10:51:00  0.000562  0.002698  0.000469
2026-04-13 10:52:00  0.000615  0.002713  0.000577
2026-04-13 10:53:00  0.000666  0.002729  0.000647
2026-04-13 10:54:00  0.000620  0.002710  0.000575
2026-04-13 10:55:00  0.000582  0.002702  0.000504
2026-04-13 10:56:00  0.000563  0.002694  0.000470

In [23]:
combined.to_csv("data/4-13-2026_rm354_FPB(clean)(vibration).csv", index=True)